### ISSUE TITLE
Crystal 1.0.0

### ISSUE THREAD

**Issue by petr-fischer** [jgaskins/neo4j.cr#9]
Hello! Can you please update Crystal version to 1.0.0 (or use `>= 0.34.0`) in the shard.yml file? Shards utility from Crystal 1.0.0 is not happy with actual state. It looks like neo4j.cr works great with Crystal 1.0.0 (`crystal spec` is all green). Thanks!

**Comment by jgaskins** [comment]
Thanks for the heads up! I completely forgot about this repo when I went on a tear updating a bunch of my others last night. 😄 I've updated the `crystal` version requirement to work until Crystal 2.0 drops and [released v0.6.1](https://github.com/jgaskins/neo4j.cr/compare/fc24a5631e09cd68f8575bf10515fb031da05a56...v0.6.1).
